services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: xy-jekyll
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - gem_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - TZ=Europe/Warsaw
    command: jekyll serve --watch --force_polling --livereload --host 0.0.0.0 --port 4000
    stdin_open: true
    tty: true

volumes:
  gem_cache:
